// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Beer struct {
	BeerID      int64
	BeerName    string
	BreweryID   int64
	Abv         sql.NullFloat64
	CreatedAt   sql.NullTime
	PackageType string
}

type Brewery struct {
	BreweryID   int64
	BreweryName string
	CreatedAt   sql.NullTime
	City        string
	State       string
}
